### ISSUE TITLE
Avatar not displayed on Firefox Mobile

### ISSUE THREAD

**Issue by quassy** [cassidyjames/cassidyjames.github.io#6]
![Screenshot_20200207-114359](https://user-images.githubusercontent.com/369996/74048063-7b91c580-499f-11ea-96d3-51630d11a4c3.png)

See attached screenshot: In the navigation bar, instead of displaying your headshot, a placeholder image and the text “Me” is displayed. It works as expected in Chrome.

BQ Aquaris X, stock Android 8.1.1, Firefox Developer Edition 68.5a1 (2020-01-15), AdBlock disabled, no other extensions

**Comment by cassidyjames** [comment]
@quassy I can't reproduce this in Firefox mobile here. Is it possible something on your phone or network is blocking Gravatar?

**Comment by quassy** [comment]
Not on my phone or network, but it seems Firefox tracking protection is the culprit and blocking requests to Gravatar. So it's on me for activating it even in normal browsing mode, but you should be able to reproduce the problem in incognito / private mode.
